### PR TITLE
Update most HTTP links to HTTPS

### PR DESCRIPTION
**Pull request by EricDunsworth**
Notes:
- Omitted sites that only work in HTTP
- Omitted sites with invalid HTTPS certificates
- Ignored /archive/ folder

### CODE REVIEW

**Comment by thekodester** [comment]
Some other update?

- https://getbootstrap.com/ too https://getbootstrap.com/docs/3.3/
- https://bootstrapdocs.com/v3.3.1/docs/components/#glyphicons too https://getbootstrap.com/docs/3.3/components/#glyphicons

This way it directs the user to the correct bootstrap version?

**Comment by EricDunsworth** [comment]
@thekodester I agree with the idea of those kinds of changes, but don't feel like they would be appropriate as a part of this PR. Its sole purpose was to update the protocol on all pre-existing HTTP links to sites that support HTTPS.

IMO changing link destinations in other ways would go beyond this PR's scope. Also, the style guide's content is probably in need of much bigger updates than just updating Bootstrap link destinations. Various other links might potentially be broken and/or pointing to sites that no longer exist.

**Comment by thekodester** [comment]
@EricDunsworth Fair point. I have update some of the links when I did the switch to jekyll. I'll maybe open an issue for that.

Otherwise I see no issue with this PR, so I we'll merge it.

**Comment by duboisp** [comment]
👍

**Pull request merged**
