### PR TITLE
Guide: Added nav elements to ToCs.

### PR DESCRIPTION
**Pull request by EricDunsworth**
Related to wet-boew/wet-boew#8177.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
@lucas-hay Would it be possible to manually restart the Travis-CI build for this PR? It looks like it randomly failed.

**Comment by EricDunsworth** [comment]
@LaurentGoderre Do you happen to know what's going on with this repo's Travis-CI builds? They all seem to be failing during setup. I believe that's the main reason this PR hasn't been merged in as of yet.

**Comment by LaurentGoderre** [comment]
The build setup here is OLD! It needs to be updated to the docker build.

**Comment by lucas-hay** [comment]
@LaurentGoderre would you be able to update this repo to the docker build

**Pull request merged**
