### PR TITLE
Fix Font Awesome Icons

### PR DESCRIPTION
**Pull request by thekodester**
All Icons Upgraded To v5

Also a shoutout to @estebandelaf for a bash script automating the process. See [fontawesome4to5.sh](https://github.com/estebandelaf/scripts/blob/master/fontawesome4to5.sh). The script may need adjusting depending on OS. I had to make some changes for MacOS.

### CODE REVIEW

**Comment by thekodester** [comment]
Went with `<code><a href="https://fontawesome.com/start" class="text-danger">&lt;link rel="stylesheet" href="https://use.fontawesome.com/releases/[version]/css/all.css" integrity="sha384-[hash]" crossorigin="anonymous"&gt;</a></code>`

Screen Shot 2019-04-17 at 6 32 07 PM

**Comment by thekodester** [comment]
Could be rewritten too `To use visit <a href="">Font Awesome</a> for the latest CDN code.`

But someone would need to write it in French.

**Comment by duboisp** [comment]
What about:

English:
```
Consult the <a href="">Font Awesome</a> website for implementation instruction.
```

French:
```
Consulter le site web de <a href="" lang="en">Font Awesome</a> pour les instructions d'implémentation.
```

**Comment by thekodester** [comment]
Perfect, we'll submit soon.

**Comment by thekodester** [comment]
Fixed.

**Comment by thekodester** [comment]
Merging now that the requested change was made.

**Pull request merged**
