### PR TITLE
Adding secondary menu documentation

### PR DESCRIPTION
**Pull request by thekodester**
Fixes/Replaces PR #247

### CODE REVIEW

**Comment by thekodester** [comment]
@duboisp

**Comment by thekodester** [comment]
Also an FYI the `written_lang: en` puts a warning on the page that it is not yet translated.

Same warning can be seen here https://wet-boew.github.io/wet-boew-styleguide/accessibility/index-fr .

**Comment by GormFrank** [comment]
Pre-approved during technical review.

**Comment by thekodester** [comment]
Merging and closing #247.

**Pull request merged**
